### ISSUE TITLE
\if@Latin undefined in bidi v20.0

### ISSUE THREAD

**Issue by seloumi** [vafa/bidi#1]
First thanks for your brilliant and useful  package.
I have updated `bidi` package to version 20.0 and I found that `\lr`  command from `xepersian ` package produce error which refer to `\if@Latin` test, I discover that  `\if@Latin` is changed to `\if@nonlatin` from your code of `bidi`,  and this was not followed by a change in the package manual. 

http://tex.stackexchange.com/q/332209/54817

**Comment by vafa** [comment]
I am afraid this is invalid. I have uploaded both packages at the same time to CTAN and there is no `\if@Latin` in either the code or the documentation of both packages.

**Comment by vafa** [comment]
I fixed it in the `bidi` documentation; I have to fix two other issues so once I fix them, I will upload the new version to CTAN.
